language: node_js

env:
    - HOST=github.com DRIVER=webdriver CODECEPT_RELATIVE_PATH=./acceptance/ DEFAULT_WEBDRIVER_BROWSER=chrome DEFAULT_PLAYWRIGHT_BROWSER=chromium NODE_TLS_REJECT_UNAUTHORIZED=0

node_js:
    - 12

before_script:
    - curl -o- -L https://yarnpkg.com/install.sh
    - export PATH="$HOME/.yarn/bin:$PATH"

addons: # get google-chrome-stable
    chrome: stable

cache:
    npm: false

install:
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - npm i lerna

script:
    - whereis google-chrome-stable
    - whereis chromedriver
    - lerna bootstrap
    - lerna run --scope create-codeceptjs-bdd-tests test
