version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    executor:
      name: node/default

    docker: # run the steps with Docker
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: install chrome
          command: |
            wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo mv -f ~/chromedriver /usr/local/share/
            sudo chmod +x /usr/local/share/chromedriver
            sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn acceptance

workflows:
  acceptance-tests:
    jobs:
      - build-and-test
